Repository hmcts/sscs-evidence-share, pull requests merged in 2019-04, with the labels that each got.

#37 Do not use lazy init for topic consumer
  src/main/java/uk/gov/hmcts/reform/sscs/servicebus/TopicConsumer.java
Labels: ns:sscs-evidence-share-pr-37

#38 SSCS-5393 - Implement Acceptance criteria in SSCS-5293
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/AbstractFunctionalTest.java
  src/e2e/resources/appealCreatedCallback.json
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/config/EvidenceShareConfigTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/EvidenceShareServiceIt.java
  src/integrationTest/resources/appealReceivedCallbackWithMrn.json
  src/main/java/uk/gov/hmcts/reform/sscs/config/EvidenceShareConfig.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/EvidenceShareService.java
  src/main/java/uk/gov/hmcts/reform/sscs/servicebus/TopicConsumer.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/sscs/service/EvidenceShareServiceTest.java
Labels: ns:sscs-evidence-share-pr-38

#36 SSCS-5394 - docmosis dns resolution
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:sscs-evidence-share-pr-36

#42 SSCS-5416 - Use Parameter "SSC001" in send letter service
  kubernetes/deployment.template.yaml
  src/main/java/uk/gov/hmcts/reform/sscs/service/BulkPrintService.java
Labels: ns:sscs-evidence-share-pr-42

#15 SSCS-5081 - Upgrade cnp-java base to the latest
  Dockerfile
Labels: ns:sscs-evidence-share-pr-15

#55 Add app insight logging
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs-evidence-share-pr-55

#56 Remove dependency checker
  Dockerfile
  build.gradle
Labels: ns:sscs-evidence-share-pr-56

#59 Remove call to bundle and stitch before sending to bulk print
  build.gradle
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/EvidenceShareFunctionalTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/BulkPrintServiceIt.java
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/EvidenceShareServiceIt.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/BulkPrintService.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/EvidenceShareService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/sscs/service/BulkPrintServiceTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/EvidenceShareServiceTest.java
Labels: ns:sscs-evidence-share-pr-59

#62 Update idam redirect urls for each env
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:sscs-evidence-share-pr-62

#63 Switch dev and prod vaults on env
  Jenkinsfile_CNP
Labels: ns:sscs-evidence-share-pr-63

#64 Add docmosis health check
  infrastructure/main.tf
  infrastructure/output.tf
  kubernetes/deployment.template.yaml
  src/main/java/uk/gov/hmcts/reform/sscs/health/DocmosisHealthIndicator.java
  src/test/java/uk/gov/hmcts/reform/sscs/health/DocmosisHealthIndicatorTest.java
Labels: ns:sscs-evidence-share-pr-64

#65 Deal with CVE-2019-0232 issue
  build.gradle
Labels: ns:sscs-evidence-share-pr-65

#66 Set tf log level to debug in jenkins
  Jenkinsfile_CNP
Labels: ns:sscs-evidence-share-pr-66

#72 Use correct vault for Docmosis based on env
  Jenkinsfile_CNP
Labels: ns:sscs-evidence-share-pr-72
