Repository hmcts/sscs-evidence-share, pull requests merged in 2020-08, with the labels that each got.

#575 Update pipeline method call
  Jenkinsfile_CNP
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-575

#586 Fix the build on master
  Jenkinsfile_CNP
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-586

#582 SSCS-7796 - Create new digital flag in the Robotics JSON
  src/main/java/uk/gov/hmcts/reform/sscs/robotics/json/RoboticsJsonMapper.java
  src/main/resources/schema/sscs-robotics.json
  src/test/java/uk/gov/hmcts/reform/sscs/robotics/json/RoboticsJsonMapperTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-582

#598 Nightly tests
  Jenkinsfile_nightly
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-598

#599 Add dm store for nightly tests
  Jenkinsfile_nightly
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-599

#533 Wla 531
  Jenkinsfile_nightly
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/config/DocmosisTemplateConfigTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/IssueFurtherEvidenceServiceIt.java
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/ReissueFurtherEvidenceServiceIt.java
  src/integrationTest/resources/config/application_it.properties
  src/main/java/uk/gov/hmcts/reform/sscs/config/DocmosisTemplateConfig.java
  src/main/java/uk/gov/hmcts/reform/sscs/robotics/json/RoboticsJsonMapper.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/FurtherEvidenceService.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/TemplateService.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/placeholders/PlaceholderConstants.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/placeholders/PlaceholderService.java
  src/main/resources/application.yaml
  src/main/resources/schema/sscs-robotics.json
  src/test/java/uk/gov/hmcts/reform/sscs/robotics/json/RoboticsJsonMapperTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/FurtherEvidenceServiceTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/TemplateServiceTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/placeholders/PlaceholderServiceTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-533

#604 SSCS-7535 Up common for isScottish
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-604

#611 enabled security scan
  Jenkinsfile_nightly
  audit.json
  security.sh
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-611

#593 SSCS-7309 - Set 'Previous State' field when case moves to dormant
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-593

#621 Remove unused tf remote state
  infrastructure/state.tf
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-621

#619 change state
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/DwpUploadResponseHandler.java
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/DwpUploadResponseHandlerTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-619

#623 changed High to Medium
  security.sh
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-623
