Repository hmcts/sscs-evidence-share, pull requests merged in 2020-02, with the labels that each got.

#422 Add robotics_email_pip_ae_to to jenkins file
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
Labels: ns:sscs, rel:sscs-evidence-share-pr-422

#423 SSCS-6947 Add app insights config
  Jenkinsfile_CNP
  charts/sscs-evidence-share/Chart.yaml
  charts/sscs-evidence-share/values.yaml
  infrastructure/main.tf
Labels: ns:sscs, rel:sscs-evidence-share-pr-423

#424 Add AppInsightsInstrumentationKey key to bootstrap
  src/main/resources/bootstrap.yaml
Labels: ns:sscs, rel:sscs-evidence-share-pr-424

#426 Sscs 7145 sscs 7223 venue airlookup changes
  build.gradle
Labels: ns:sscs, rel:sscs-evidence-share-pr-426

#430 SSCS-7273 Use the correct case created date when generating dl6
  Jenkinsfile_CNP
  build.gradle
  charts/sscs-evidence-share/Chart.yaml
  charts/sscs-evidence-share/values.preview.template.yaml
  config/checkstyle/checkstyle.xml
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ReissueAppellantAppointeeFurtherEvidenceHandlerFunctionalTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/placeholders/PlaceholderServiceIt.java
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/ReissueFurtherEvidenceHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/SendToBulkPrintHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/config/EvidenceShareConfig.java
  src/main/java/uk/gov/hmcts/reform/sscs/config/SmtpConfig.java
  src/main/java/uk/gov/hmcts/reform/sscs/factory/DocumentRequestFactory.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/placeholders/PlaceholderService.java
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/ReissueFurtherEvidenceHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/SendToBulkPrintHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/factory/DocumentRequestFactoryTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/placeholders/PlaceholderServiceTest.java
Labels: ns:sscs, rel:sscs-evidence-share-pr-430

#431 SSCS-7275 Update logo on documents
  src/main/resources/application.yaml
Labels: ns:sscs, rel:sscs-evidence-share-pr-431
