Repository hmcts/sscs-evidence-share, pull requests merged in 2021-11, with the labels that each got.

#1163 suppress spring dependency check until version upgraded
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1163

#1165 Child support NPE fix
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/IssueFurtherEvidenceHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/SendToBulkPrintHandler.java
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1165

#1164 SSCS-9733: ExUI – Correct venue name on final decision and adjournmen…
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1164

#1170 Sscs 9750 amend gaps venue
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1170

#1149 Sscs 9668 child support upload response event
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/DwpUploadResponseHandler.java
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/DwpUploadResponseHandlerTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1149

#1174 SSCS-9800: Common – Update list of venue addresses and new venue
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1174

#1180 SSCS-9836: Common - Update all repos to point to the latest common (4…
  build.gradle
  src/main/resources/application.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1180

#1181 SSCS-9755 Child support rep robotics fix
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1181

#1182 SSCS-9747 added status event handling for panel compositionand update…
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/ConfirmPanelCompositionHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/UpdateOtherPartyHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/PanelCompositionService.java
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/ConfirmPanelCompositionHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/UpdateOtherPartyHandlerTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1182

#1184 Revert SSCS-9777: Tribunals / Common – Change the document ordering
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1184

#1169 SSCS-9755 Child Support Robotics
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1169
