Repository hmcts/sscs-evidence-share, pull requests merged in 2021-06, with the labels that each got.

#984 Verify we have removed enough of the suppressions
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-984

#980 SSCS-8820 - JSA DWP Office Address
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-980

#993 Fix flaky nightly tests by generating ninos
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/AbstractFunctionalTest.java
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/EvidenceShareFunctionalTest.java
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/IssueFurtherEvidenceHandlerFunctionalTest.java
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ReissueAppellantAppointeeFurtherEvidenceHandlerFunctionalTest.java
  src/e2e/resources/issueFurtherEvidenceCallback.json
  src/e2e/resources/issueFurtherEvidenceExistingReasonableAdjustmentCallback.json
  src/e2e/resources/issueFurtherEvidenceReasonableAdjustmentCallback.json
  src/e2e/resources/reissueFurtherEvidenceCallback.json
  src/e2e/resources/validAppealCreatedCallback.json
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-993

#989 SSCS-8957 Maternity Allowance
  build.gradle
  src/main/java/uk/gov/hmcts/reform/sscs/service/RequestTranslationService.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/RequestTranslationServiceTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-989

#1005 Adding Contract Tests
  Jenkinsfile_CNP
  build.gradle
  lombok.config
  pacts/sscs_evidenceShare-em_dm_store.json
  pacts/sscs_evidenceShare-rpeSendLetterService_SendLetterController.json
  src/contractTest/java/uk/gov/hmcts/reform/sscs/contract/DocumentServiceConsumerTest.java
  src/contractTest/java/uk/gov/hmcts/reform/sscs/contract/SendLetterServiceConsumerApplication.java
  src/contractTest/java/uk/gov/hmcts/reform/sscs/contract/SendLetterServiceConsumerTest.java
  src/contractTest/resources/application.properties
  src/contractTest/resources/application.yml
  src/contractTest/resources/files/myPdf.pdf
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1005

#1021 suppress CVE-2021-33813
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1021

#1011 SSCS-9303 IIDB do not change state for upload response event
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/DwpUploadResponseHandler.java
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/DwpUploadResponseHandlerTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1011

#1014 SSCS-9305 Refactor after moving deprecated fields
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1014

#1029 resolve cve errors
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1029

#1031 update security script
  security.sh
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1031
