Repository hmcts/sscs-evidence-share, pull requests merged in 2021-08, with the labels that each got.

#1067 SSCS-9341 - BenefitType not found
  build.gradle
  src/main/java/uk/gov/hmcts/reform/sscs/service/placeholders/PlaceholderService.java
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1067

#1048 Fortify scan enabled
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
  lombok.config
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1048

#1073 SSCS-9435 Robotics enhanced confidentiality feature
  build.gradle
  src/main/resources/application.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1073

#1078 quick fix for functional tests
  build.gradle
  src/e2e/resources/issueFurtherEvidenceCallback.json
  src/e2e/resources/issueFurtherEvidenceExistingReasonableAdjustmentCallback.json
  src/e2e/resources/issueFurtherEvidenceReasonableAdjustmentCallback.json
  src/e2e/resources/reissueFurtherEvidenceCallback.json
  src/e2e/resources/reissueFurtherEvidenceReasonableAdjustmentCallback.json
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1078

#1077 SSCS-9508 - BSPS - dwpAddress JSON
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1077

#1080 SSCS-9506 - Change Benefit name to Jobseeker’s Allowance (JSA)
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1080

#1084 SSCS-9502: Change Benefit name from Pension Credits to Pension Credit
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1084
