Repository hmcts/sscs-evidence-share, pull requests merged in 2021-12, with the labels that each got.

#1186 SSCS-9747 changed due date
  src/main/java/uk/gov/hmcts/reform/sscs/service/PanelCompositionService.java
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/ConfirmPanelCompositionHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/UpdateOtherPartyHandlerTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1186

#1189 CVE-2021-22096 fix
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1189

#1187 Revert SSCS-9777: Tribunals / Common – Change the document ordering
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1187

#1191 SSCS-9862 Send further evidence to other parties
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/IssueFurtherEvidenceServiceIt.java
  src/integrationTest/resources/issueFurtherEvidenceCallbackWithMultipleOtherPartyRepEvidence.json
  src/integrationTest/resources/issueFurtherEvidenceCallbackWithOtherPartyAppointeeEvidence.json
  src/integrationTest/resources/issueFurtherEvidenceCallbackWithOtherPartyEvidence.json
  src/integrationTest/resources/issueFurtherEvidenceCallbackWithOtherPartyRepEvidence.json
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/HandlerUtils.java
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/IssueFurtherEvidenceHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/ReissueFurtherEvidenceHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/domain/FurtherEvidenceLetterType.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/CoverLetterService.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/FurtherEvidenceService.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/SscsDocumentService.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/placeholders/FurtherEvidencePlaceholderService.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/placeholders/PlaceholderConstants.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/placeholders/PlaceholderService.java
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/IssueFurtherEvidenceHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/ReissueFurtherEvidenceHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/CoverLetterServiceTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/FurtherEvidenceServiceTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/SscsDocumentServiceTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/placeholders/FurtherEvidencePlaceholderServiceTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/placeholders/PlaceholderServiceTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1191

#1195 upgrade log4j to 2.15.0
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1195

#1201 SSCS-9743: Child Support - otherPartyAdded Notification
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1201

#1198 SSCS-9871 refactor to common reissue FE
  build.gradle
  src/e2e/resources/reissueFurtherEvidenceCallback.json
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/ReissueFurtherEvidenceHandler.java
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/ReissueFurtherEvidenceHandlerTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1198
