Repository hmcts/sscs-evidence-share, pull requests merged in 2021-03, with the labels that each got.

#841 SSCS-8750 - Dwp Document Sorting
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-841

#847 fixed the dependency check
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-847

#852 fixed the dependency check
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-852

#854 fixed the dependency check
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-854

#858 SSCS-8829:Add Welsh flag - RIP1 Document
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-858

#869 SSCS-8884: Evidence share – Update PIP AE e-mail address to correct one
  src/main/resources/bootstrap.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-869

#875 Sscs 8827 single case to draft v3
  build.gradle
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/AppealReceivedHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/ReciprocalLinkHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/SendToBulkPrintHandler.java
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/AppealReceivedHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/ReciprocalLinkHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/SendToBulkPrintHandlerTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-875

#880 SSCS-8916 - WTU email in pre prod
  src/main/resources/application.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-880

#878 Sscs 8861 rip1 document translation
  build.gradle
  src/main/java/uk/gov/hmcts/reform/sscs/service/RequestTranslationService.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/RequestTranslationServiceTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-878

#884 SSCS-8968 - Robotics – PIP AE isn't showing correctly for DwpOriginatingOffice and DwpPresentingOffice
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-884

#892 Upgrade pdfbox dependency
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-892

#894 Remove unused suppressions
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-894

#895 Remove unused dependency suppression
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-895

#891 SSCS-8894:Carer's Allowance - Airlookup, DWP addresses & Robot Config…
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-891

#898 DTSPO-1792 Bump common libraries after moving from bintray to jitpack
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-898
