Repository hmcts/sscs-evidence-share, pull requests merged in 2021-07, with the labels that each got.

#1032 suppress for a month again
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1032

#1037 SSCS-9061-updated common with social fund benefit
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1037

#1035 SSCS-9378: Resize documents issue seen on representative documents
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1035

#1018 SSCS-9308 - CCD UI – Setting the ESA and UC dwpRegionalCentrer
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1018

#1045 SSCS-8924 - Income Support
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1045

#1046 SSCS-9362 - Secure doc store
  build.gradle
  src/main/java/uk/gov/hmcts/reform/sscs/SscsEvidenceShareApplication.java
  src/main/resources/application.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1046

#1053 fix dc
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1053

#1050 SSCS-9420 - Update doc store client
  build.gradle
  src/main/java/uk/gov/hmcts/reform/sscs/SscsEvidenceShareApplication.java
  src/main/resources/application.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1050

#1058 SSCS-9208 Other benefits
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1058

#1066 SSCS-7510 Add Scottish Excela properties
  src/contractTest/resources/application.properties
  src/contractTest/resources/application.yml
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/placeholders/PlaceholderServiceIt.java
  src/main/java/uk/gov/hmcts/reform/sscs/config/ExelaAddressConfig.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/placeholders/PlaceholderService.java
  src/main/resources/application.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1066

#1070 SSCS-7510 Scottish PO box feature flag
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/placeholders/PlaceholderServiceIt.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/placeholders/PlaceholderService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/sscs/service/placeholders/PlaceholderServiceTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1070
