Repository hmcts/sscs-evidence-share, pull requests merged in 2021-04, with the labels that each got.

#902 suppress CVE-2017-6888
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-902

#903 revert SSCS-8894
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-903

#908 Bump pdf common 1.4.31
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-908

#912 SSCS-9046 - fix DC failures
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-912

#870 SSCS-8855 PDF Resizing
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/IssueFurtherEvidenceServiceIt.java
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/ReissueFurtherEvidenceServiceIt.java
  src/integrationTest/resources/myPdf.pdf
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/IssueFurtherEvidenceHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/ReissueFurtherEvidenceHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/model/PdfDocument.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/FurtherEvidenceService.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/SscsDocumentService.java
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/IssueFurtherEvidenceHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/ReissueFurtherEvidenceHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/FurtherEvidenceServiceTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/SscsDocumentServiceTest.java
  src/test/resources/myPdf.pdf
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-870

#910 SSCS-9037: Review how RPCs is calculated via the Airlookup file
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-910

#914 SSCS-9031 Carers allowance camel case fix
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-914

#919 SSCS-9050 - DLA - Update Welsh SSCS1 Form
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-919

#922 SSCS-8995: CCD UI – Add HMCTS to original senders
  build.gradle
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/IssueFurtherEvidenceHandler.java
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/IssueFurtherEvidenceHandlerTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-922
