Repository hmcts/sscs-evidence-share, pull requests merged in 2022-09, with the labels that each got.

#1372 SSCS-10841 Common bump
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1372

#1374 Update renovate.json
  .github/renovate.json
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1374

#1377 Move sscs-common declaration
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1377

#1381 Update renovate.json
  .github/dependabot.yml
  .github/renovate.json
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1381

#1388 SSCS-10901 Add helm alias
  .github/renovate.json
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1388

#1389 SSCS-10901 Fix renovate json
  .github/renovate.json
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1389

#1373 SSCS-10882 Fixing Conflicting IDs
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1373

#1393 SSCS-10909 Removal of suppressions
  build.gradle
  config/owasp/suppressions.xml
  src/functionalTest/java/helper/EnvironmentProfileValueSource.java
  src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/AbstractFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/AppealToProceedFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/DwpUploadFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/EvidenceShareFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/IssueDirectionFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/IssueFurtherEvidenceHandlerFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/ManualCaseCreatedFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/ReissueAppellantAppointeeFurtherEvidenceHandlerFunctionalTest.java
  src/functionalTest/resources/appealToProceedCallback.json
  src/functionalTest/resources/directionIssuedCallback.json
  src/functionalTest/resources/dwpUploadResponseCallback.json
  src/functionalTest/resources/evidence-document.pdf
  src/functionalTest/resources/existing-document.pdf
  src/functionalTest/resources/issueFurtherEvidenceCallback.json
  src/functionalTest/resources/issueFurtherEvidenceExistingReasonableAdjustmentCallback.json
  src/functionalTest/resources/issueFurtherEvidenceFaultyCallback.json
  src/functionalTest/resources/issueFurtherEvidenceReasonableAdjustmentCallback.json
  src/functionalTest/resources/reissueFurtherEvidenceCallback.json
  src/functionalTest/resources/reissueFurtherEvidenceReasonableAdjustmentCallback.json
  src/functionalTest/resources/validAppealCreatedCallback.json
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1393
