Repository hmcts/sscs-evidence-share, pull requests merged in 2022-10, with the labels that each got.

#1394 SSCS-10917 Commons bump
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1394

#1399 SSCS-10968 cve suppresion
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1399

#1400 SSCS-10985 CVE Fix Commons Bump
  build.gradle
  config/owasp/suppressions.xml
  lombok.config
  src/main/java/uk/gov/hmcts/reform/sscs/service/RequestTranslationService.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/RoboticsService.java
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1400

#1410 Commons bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1410

#1413 SSCS-11063 Use Renovate Shared Preset
  .github/renovate.json
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1413

#1395 SSCS-10924 Change to tf managed secret
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  charts/sscs-evidence-share/Chart.yaml
  charts/sscs-evidence-share/values.yaml
  src/main/resources/bootstrap.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1395
