Repository hmcts/sscs-evidence-share, pull requests merged in 2022-08, with the labels that each got.

#1360 extend suppression dates
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1360

#1361 SSCS-10805-jar-version-update
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1361

#1364 SSCS-10773: Update commons version
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1364

#1367 chore: increment sscs-common version
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1367

#1368 Add backstage configuration file
  catalog-info.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1368

#1362 sscs-9874-common-version-update
  build.gradle
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/IssueFurtherEvidenceHandlerFunctionalTest.java
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ReissueAppellantAppointeeFurtherEvidenceHandlerFunctionalTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/IssueFurtherEvidenceServiceIt.java
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1362

#1370 SSCS-10841 Common bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1370
