Repository hmcts/sscs-evidence-share, pull requests merged in 2022-05, with the labels that each got.

#1296 SSCS-10223 Update callback handler
  build.gradle
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/RoboticsCallbackHandler.java
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/RoboticsCallbackHandlerTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1296

#1283 SSCS-10388 Update Commons
  build.gradle
  config/owasp/suppressions.xml
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/service/RoboticsServiceIt.java
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/HandlerUtils.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/placeholders/FurtherEvidencePlaceholderService.java
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/DwpUploadResponseHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/HandlerUtilsTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/FurtherEvidenceServiceTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/placeholders/FurtherEvidencePlaceholderServiceTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1283

#1298 SSCS-10444 Change CVE Reporting
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1298

#1300 Sscs 10443 azure tagging
  infrastructure/main.tf
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1300

#1307 Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1307

#1294 SSCS-10349 populate case access management fields on ManualCaseCreatedHandler callback
  build.gradle
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/ManualCaseCreatedHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/helper/CaseAccessManagementFieldsHelper.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/PanelCompositionService.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/TemplateService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/HandlerHelper.java
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/IssueFurtherEvidenceHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/ManualCaseCreatedHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/RequestTranslationCallbackHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/helper/CaseAccessManagementFieldsHelperTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/TemplateServiceTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1294

#1308 SSCS-10490 bump common
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1308

#1311 Fix Nightly Builds
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1311

#1315 SSCS-10552-Upgrade-Tomcat: upgrade tomcat
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1315

#1316 SSCS-10116 Bump SSCS Commons
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1316

#1319 SSCS-10555 upgraded spring core
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1319

#1321 SSCS-10561: Dependency Fix
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1321

#1322 Sscs 10568 fix suppression
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1322
