Repository hmcts/sscs-evidence-share, pull requests merged in 2022-04, with the labels that each got.

#1274 Update build.gradle
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1274

#1279 SSCS-10220 Update to common RC version
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1279

#1287 Update commons
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1287

#1276 SSCS-10146 update sscs-common version
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1276

#1288 SSCS-10387 Update Commons
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1288

#1293 SSCS-10440 Update Springboot Cre
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1293
