Repository hmcts/sscs-evidence-share, pull requests merged in 2022-12, with the labels that each got.

#1453 Sscs 11165 pre commit hooks
  build.gradle
  config/git/pre-commit
  lombok.config
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1453

#1458 SSCS-11249 - CVE suppression
  config/git/pre-commit
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1458

#1463 SSCS-11249-2 - Ignore OWASP Zaproxy
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1463
