Repository hmcts/sscs-evidence-share, pull requests merged in 2022-11, with the labels that each got.

#1427 Tomcat to 9.0.68
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1427

#1432 SSCS-11169 - upgrade jackson-databind
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1432

#1425 Sscs 11050 upgrade spring to v2.7.5 for evidence share
  build.gradle
  src/contractTest/resources/application.properties
  src/main/java/uk/gov/hmcts/reform/sscs/SscsEvidenceShareApplication.java
  src/main/java/uk/gov/hmcts/reform/sscs/config/SwaggerConfiguration.java
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1425
