Repository hmcts/sscs-evidence-share, pull requests merged in 2022-07, with the labels that each got.

#1343 SSCS-10349 Use update case only to update CAM fields.
  build.gradle
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/ManualCaseCreatedHandler.java
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/ManualCaseCreatedHandlerTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1343

#1347 Turn-Cardiff-LA-On-Common-Bump
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1347

#1349 SSCS-10706 Update pdf email common
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1349

#1350 sscs-10746 update for suppress CVE-2022-31569
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1350

#1352 SSCS-10087 Commons Bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1352

#1351 sscsBaseChartUpdate-Java401
  charts/sscs-evidence-share/Chart.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1351

#1356 alias added for use by non-prod envs
  infrastructure/main.tf
  infrastructure/providers.tf
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1356

#1357 alias added for use by non-prod envs
  infrastructure/main.tf
  infrastructure/providers.tf
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1357

#1358 count turned off
  infrastructure/main.tf
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1358
