Repository hmcts/sscs-evidence-share, pull requests merged in 2022-01, with the labels that each got.

#1199 Upgrade log4j to 2.16.0
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1199

#1209 Sscs 9870
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/ReissueFurtherEvidenceHandler.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/ReissueFurtherEvidenceHandlerTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1209

#1226 Bump common to 4.6.31
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1226

#1219 SSCS-9860 SSCS5 - Upload response event
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/DwpUploadResponseHandler.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/DwpUploadResponseHandlerTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1219

#1228 Bump common 4.6.32
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1228

#1227 SSCS-9841 Robotics for sscs5
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1227
