Repository hmcts/sscs-evidence-share, pull requests merged in 2022-06, with the labels that each got.

#1324 SSCS-10445 Commons Bump
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1324

#1327 Update build.gradle
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1327

#1330 SSCS-10286 Commons Bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1330

#1333 SSCS-10643-Reference Data Update
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1333

#1334 SSCS-10620 Commons Bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1334

#1335 SSCS-10242 Commons Bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1335

#1340 SSCS-10178 Commons Bump
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1340
