Repository hmcts/sscs-evidence-share, pull requests merged in 2024-04, with the labels that each got.

#1618 SSCSSI-34: Make jms listener conditional
  src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/ManualCaseCreatedFunctionalTest.java
  src/main/java/uk/gov/hmcts/reform/sscs/servicebus/TopicConsumer.java
  src/main/java/uk/gov/hmcts/reform/sscs/servicebus/messaging/MessagingConfig.java
  src/main/resources/application.yaml
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-evidence-share-pr-1618

#1621 SSCSSI-34: Bump existing suppression dates
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1621

#1623 Archive repo as functionality moved to Tribs API
  README.md
Labels: ns:sscs, prd:sscs, rel:sscs-evidence-share-pr-1623
